services:
  windows:
    image: beast0823/windows
    container_name: windows
    environment:
      VERSION: "2025"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
      USERNAME: "mar"
      PASSWORD: "marpogi"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
